In [30]:
import pandas as pd

In [31]:
train_cross_df = pd.read_csv('train_dataset_passed_cross_mining_method_validated_df.csv')
train_cross_df.head()

,Unnamed: 0,question,positive,hard_negative,soft_negative,hard_negative_valid,soft_negative_valid,hardness_score
0,10973,What is the purpose of obfuscating or encrypti...,Resource fork content may be obfuscated/encryp...,The purpose of encrypting and/or encoding file...,Developing and publishing policies that define...,True,True,4
1,17880,What types of traffic patterns should be monit...,Extraneous packets that do not belong to estab...,Traffic patterns that do not belong to establi...,1 tactic is used in attack technique 'T1564.00...,True,True,5
2,2013,How does attack software 'S0223: POWERSTATS' u...,POWERSTATS uses attack technique 'T1132.001: S...,PowerShower uses the 'T1132.001: Standard Enco...,The parent technique of attack technique 'T102...,True,True,4
3,14434,How does attack software 'S0446: Ryuk' use att...,Ryuk has used the C$ network share for lateral...,NotPetya uses PsExec to interact with the ADMI...,IcedID has employed obfuscated VBA string expr...,True,True,3
4,16392,Which tactics are used in attack technique 'T1...,1 tactic is used in attack technique 'T1596.00...,1 tactic is used in attack technique 'T1596.00...,A silver ticket is a Kerberos ticket granting ...,True,True,5

In [32]:
qa_only_train_cross_df = train_cross_df[['question', 'positive', 'hard_negative', 'soft_negative']]
qa_only_train_cross_df.head()

,question,positive,hard_negative,soft_negative
0,What is the purpose of obfuscating or encrypti...,Resource fork content may be obfuscated/encryp...,The purpose of encrypting and/or encoding file...,Developing and publishing policies that define...
1,What types of traffic patterns should be monit...,Extraneous packets that do not belong to estab...,Traffic patterns that do not belong to establi...,1 tactic is used in attack technique 'T1564.00...
2,How does attack software 'S0223: POWERSTATS' u...,POWERSTATS uses attack technique 'T1132.001: S...,PowerShower uses the 'T1132.001: Standard Enco...,The parent technique of attack technique 'T102...
3,How does attack software 'S0446: Ryuk' use att...,Ryuk has used the C$ network share for lateral...,NotPetya uses PsExec to interact with the ADMI...,IcedID has employed obfuscated VBA string expr...
4,Which tactics are used in attack technique 'T1...,1 tactic is used in attack technique 'T1596.00...,1 tactic is used in attack technique 'T1596.00...,A silver ticket is a Kerberos ticket granting ...

In [33]:
len(qa_only_train_cross_df)

15308

In [34]:
train_oracle_df = pd.read_csv('train_dataset_passed_oracle_method_vlidated_df.csv')
train_oracle_df.head()

,Unnamed: 0,question,positive,hard_negative,soft_negative,sim_q_pd,hard_neg_sim,soft_neg_sim,hard_negative_valid,soft_negative_valid,hardness_score
0,5901,How does attack software 'S0484: Carberp' use ...,Carberp's passw.plug plugin can gather passwor...,The software procedures that use attack techni...,Web Credential Usage can be used to detect att...,0.383338,0.570575,0.267038,True,True,3
1,10227,How does attack software 'S0181: FALLCHILL' us...,FALLCHILL can modify file or directory timesta...,The attack software 'S0352: OSX_OCEANLOTUS.D' ...,The attack techniques used by software 'S0151:...,0.319442,0.646252,0.270010,True,True,3
2,14237,Discuss the role of artificial intelligence in...,"AI is used for threat detection, pattern recog...",Cognitive Cybersecurity is using AI that relie...,If you do not have charge of the Risk Register...,0.550083,0.692150,0.397320,True,True,4
3,1908,How does attack software 'S1058: Prestige' use...,Prestige has been deployed using the Default D...,The software procedures that use attack techni...,The attack groups that used software 'S0139: P...,0.297054,0.564861,0.232010,True,True,3
4,6342,How does attack software 'S0410: Fysbis' use a...,Fysbis has the ability to create and execute c...,The attack techniques used by software 'S0410:...,The attack groups that used software 'S0150: P...,0.296920,0.518224,0.241296,True,True,3

In [35]:
qa_only_train_oracle_df = train_oracle_df[['question', 'positive', 'hard_negative', 'soft_negative']]
qa_only_train_oracle_df.head()

,question,positive,hard_negative,soft_negative
0,How does attack software 'S0484: Carberp' use ...,Carberp's passw.plug plugin can gather passwor...,The software procedures that use attack techni...,Web Credential Usage can be used to detect att...
1,How does attack software 'S0181: FALLCHILL' us...,FALLCHILL can modify file or directory timesta...,The attack software 'S0352: OSX_OCEANLOTUS.D' ...,The attack techniques used by software 'S0151:...
2,Discuss the role of artificial intelligence in...,"AI is used for threat detection, pattern recog...",Cognitive Cybersecurity is using AI that relie...,If you do not have charge of the Risk Register...
3,How does attack software 'S1058: Prestige' use...,Prestige has been deployed using the Default D...,The software procedures that use attack techni...,The attack groups that used software 'S0139: P...
4,How does attack software 'S0410: Fysbis' use a...,Fysbis has the ability to create and execute c...,The attack techniques used by software 'S0410:...,The attack groups that used software 'S0150: P...

In [36]:
len(qa_only_train_oracle_df)

8882

In [37]:
all_df = pd.concat(
    [
        pd.read_csv("attackqa_parquet_processed_all.csv")[["question", "answer"]],
        pd.read_csv("cybersecurityQAAdataset_only_reviewed_by_expert.csv")[["question", "answer"]],
        pd.read_csv("cybersecurity_qa_updated_column_names.csv")[["question", "answer"]]
    ],
    ignore_index=True
).drop_duplicates().reset_index(drop=True)
all_df.head()

,question,answer
0,What is a potential indicator of the 'T1539: S...,A potential indicator of the 'T1539: Steal Web...
1,How can the 'Process Access' data component be...,The 'Process Access' data component can be use...
2,What is the path to the maps file in the /proc...,The maps file is stored under the path /proc/<...
3,What is the potential consequence of malicious...,The potential consequence of malicious code in...
4,What is an abnormal call to a higher privilege...,An abnormal call to a higher privileged proces...

In [55]:
len(all_df)

26281

In [39]:
all_df.rename(columns={"answer": "positive"}, inplace=True)
all_df.head()

,question,positive
0,What is a potential indicator of the 'T1539: S...,A potential indicator of the 'T1539: Steal Web...
1,How can the 'Process Access' data component be...,The 'Process Access' data component can be use...
2,What is the path to the maps file in the /proc...,The maps file is stored under the path /proc/<...
3,What is the potential consequence of malicious...,The potential consequence of malicious code in...
4,What is an abnormal call to a higher privilege...,An abnormal call to a higher privileged proces...

In [56]:
all_df["positive"].duplicated().sum()

394

In [40]:
len(pd.concat([qa_only_train_cross_df[['question', 'positive']], qa_only_train_oracle_df[['question', 'positive']]]))

24190

In [41]:
exclude_df = pd.concat([
    qa_only_train_cross_df[['question', 'positive']], qa_only_train_oracle_df[['question', 'positive']]
]).drop_duplicates()
exclude_df.head()

,question,positive
0,What is the purpose of obfuscating or encrypti...,Resource fork content may be obfuscated/encryp...
1,What types of traffic patterns should be monit...,Extraneous packets that do not belong to estab...
2,How does attack software 'S0223: POWERSTATS' u...,POWERSTATS uses attack technique 'T1132.001: S...
3,How does attack software 'S0446: Ryuk' use att...,Ryuk has used the C$ network share for lateral...
4,Which tactics are used in attack technique 'T1...,1 tactic is used in attack technique 'T1596.00...

In [42]:
len(exclude_df)

18750

In [43]:
merged_df = pd.merge(all_df, exclude_df, on=['question', 'positive'], how='left', indicator=True)

In [44]:
merged_df.head()

,question,positive,_merge
0,What is a potential indicator of the 'T1539: S...,A potential indicator of the 'T1539: Steal Web...,left_only
1,How can the 'Process Access' data component be...,The 'Process Access' data component can be use...,both
2,What is the path to the maps file in the /proc...,The maps file is stored under the path /proc/<...,left_only
3,What is the potential consequence of malicious...,The potential consequence of malicious code in...,left_only
4,What is an abnormal call to a higher privilege...,An abnormal call to a higher privileged proces...,both

In [45]:
semi_fineal_test_df = merged_df[merged_df['_merge'] == 'left_only'].drop(columns=['_merge'])

In [46]:
semi_fineal_test_df.head()

,question,positive
0,What is a potential indicator of the 'T1539: S...,A potential indicator of the 'T1539: Steal Web...
2,What is the path to the maps file in the /proc...,The maps file is stored under the path /proc/<...
3,What is the potential consequence of malicious...,The potential consequence of malicious code in...
5,What are the two techniques used by tools to a...,"Tools such as Meterpreter, Cobalt Strike, and ..."
6,What is the potential outcome of modifying acc...,The potential outcome of modifying access toke...

In [47]:
len(semi_fineal_test_df)

7531

In [48]:
negatives_cross = pd.concat([
    qa_only_train_cross_df['hard_negative'],
    qa_only_train_cross_df['soft_negative']
]).dropna()

In [49]:
negatives_oracle = pd.concat([
    qa_only_train_oracle_df['hard_negative'],
    qa_only_train_oracle_df['soft_negative']
]).dropna()

In [50]:
all_negatives = set(pd.concat([negatives_cross, negatives_oracle]))

In [51]:
final_test_df = semi_fineal_test_df[
    ~semi_fineal_test_df['positive'].isin(all_negatives)
].reset_index(drop=True)

In [52]:
len(final_test_df)

1978

In [53]:
final_test_df.head()

,question,positive
0,What is a potential indicator of the 'T1539: S...,A potential indicator of the 'T1539: Steal Web...
1,What is the potential outcome of modifying acc...,The potential outcome of modifying access toke...
2,What is the purpose of Analytic 1 - Command La...,The purpose of Analytic 1 - Command Launched f...
3,What is the primary goal of the 'T1137.006: Ad...,The primary goal of the 'T1137.006: Add-ins' a...
4,What is an instance of the process at.exe runn...,An instance of the process at.exe running impl...

In [58]:
final_test_df['positive'].duplicated().sum()

0

In [54]:
# final_test_df.to_csv('final_full_test_df.csv', index=False)

In [29]:
# final_full_test_df.to_csv('final_full_test_df.csv', index=False)